package com.neosoft.userapppocjwttoken.controller;



import com.neosoft.userapppocjwttoken.entity.UserMaster;
import com.neosoft.userapppocjwttoken.model.UserRequest;
import com.neosoft.userapppocjwttoken.model.UserResponse;
import com.neosoft.userapppocjwttoken.service.IUserService;
import com.neosoft.userapppocjwttoken.util.JwtUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;

@RestController
@RequestMapping("/user")
public class UserController {
	
	@Autowired
	private IUserService userService;

	@Autowired
	private AuthenticationManager authenticationManager;

	@Autowired
	private JwtUtil jwtUtil;


	//2. Save User details .
	@PostMapping("/save")
	public UserMaster saveUserData(@Valid  @RequestBody UserMaster userMaster){
		return userService.saveUserData(userMaster);
	}


	//2. Validate User details and generate the token.
	@PostMapping("/login")
	public ResponseEntity<UserResponse>  loginUser(@RequestBody UserRequest userRequest){
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						userRequest.getUsername(),
						userRequest.getPassword()
				));
		String token = jwtUtil.generateToken(userRequest.getUsername());
		return ResponseEntity.ok(
				new UserResponse(token, "Success!  Generated by NeoSoft-Moti"));
	}


	@GetMapping("/get/{userMasterId}")
	public UserMaster fetchUserById(@PathVariable("userMasterId") int userMasterId){

		return userService.findUserById(userMasterId);
	}

	@GetMapping("/fetch/{department}")
	public UserMaster fetchUser(@PathVariable("department") String department){

		return userService.findUserByDepartment(department);
	}


	@GetMapping("/search")
	public ResponseEntity<List<UserMaster>> searchUserMasterData(@RequestParam("query") String query){
		return ResponseEntity.ok(userService.searchUserMaster(query));
	}

	/*//3.After login only
	@PostMapping("welcome")
	public  ResponseEntity<String>  accessData(Principal principal){
		return ResponseEntity.ok("Hello User!" +principal.getName());
	}*/

	@GetMapping("/users")
	public List<UserMaster> getAllUserData(){
		return userService.findAllUserData();
	}

	/*@GetMapping("/users")
	public ResponseEntity<?> getAllUser() {

		List<User> userList = userService.findAllUser();
		System.out.println("userList: " + userList);
		return new ResponseEntity<>(userList, userList.size() > 0 ? HttpStatus.OK : HttpStatus.NOT_FOUND);
	}*/

}
